import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Spline_Sans_Mono } from "next/font/google"

const spline_sans_mono = Spline_Sans_Mono({
	subsets: ['latin'],
	weight: ['300', '400', '500', '600', '700']
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
	return (
	<html lang="en">
		<ClerkProvider>
			<body className={`${spline_sans_mono.className}`} >
				{children}
			</body>
		</ClerkProvider>
	</html>
	);
}
